name: Publish

on:
  push:
    branches: ['main']

permissions:
  contents: read

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      new_release_published: ${{ steps.semantic-release.outputs.new_release_published }}
      new_release_version: ${{ steps.semantic-release.outputs.new_release_version }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0

      - id: semantic-release
        uses: cycjimmy/semantic-release-action@b12c8f6015dc215fe37bc154d4ad456dd3833c90 # v6.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    name: Publish
    needs: release
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7
        with:
          go-version-file: 'go.mod'

      - uses: ko-build/setup-ko@61b4d1d396f5b2e7d6bb6fefdce3dc38d1a13445 # v0.10

      - name: Build and publish image
        env:
          NEW_RELEASE_PUBLISHED: ${{ needs.release.outputs.new_release_published }}
          NEW_RELEASE_VERSION: ${{ needs.release.outputs.new_release_version }}
        run: |
          tags="latest,${{ github.sha }}"
          if [ "$NEW_RELEASE_PUBLISHED" = "true" ]; then
            tags="${tags},v${NEW_RELEASE_VERSION}"
          fi
          ko build -B --tags "$tags" ./cmd/sklop
